apiVersion: datasource.external.crossplane.io/v1alpha1
kind: DataSource
metadata:
  name: example
spec:
  forProvider:
    type: configmap
    configMapRef:
      name: my-values
  providerConfigRef:
    name: example